### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by jcliu0428** [samiragarwala/PlaneFormers#3]
Thank you for the great work! A question from my side, how to evaluate the pre-trained model on your testing set? I've seen the evaluation code but the configuration parameters are too complicated. Is there any quick bash command to use to verify the results corresponding to the paper? Thanks.

**Comment by samiragarwala** [comment]
Thank you for your interest in our work! I've provided the two-view evaluation steps below and will provide the multi-view evaluation steps in a follow-up comment.

1) Setup the 2-view dataset from [SparsePlanes](https://github.com/jinlinyi/SparsePlanes/blob/main/docs/data.md) and generate a plane embedding dataset as per #2. We evaluate plane correspondences using a GT bounding box dataset for planes, while AP and camera pose is evaluated using a predicted bounding box dataset and thus you will need to generate both types of embedding datasets.

2) Generate the optimized dictionary (i.e. evaluation file) from the pre-trained model using the following command:
`python train.py --gen_eval_file --output_file <output .pkl file name> --eval_ckpt ./models/planeformers_eccv.pt --json_path <path to directory containing data jsons from SparsePlanes> --path <path to plane embedding dataset> --kmeans_rot ./SparsePlanes/sparsePlane/models/kmeans_rots_32.pkl --kmeans_trans ./SparsePlanes/sparsePlane/models/kmeans_trans_32.pkl --eval_set test --camera_search_len 3 --plane_corr_threshold 0.7 --emb_format plane_params --model_name plane_camera_corr --eval_add_cam_residual --write_new_eval_file --use_plane_params --use_appearance_embeddings --use_plane_mask --transformer_on --model_name plane_camera_corr`

Alternatively, I've also attached the [optimized dictionaries for the GT and predicted box](https://github.com/samiragarwala/PlaneFormers/files/9847626/2-view-opt-dicts.zip) cases for the evaluation step.

3) Evaluate the pretrained model on the two-view case by running the [SparsePlanes evaluation code](https://github.com/jinlinyi/SparsePlanes/blob/main/docs/eval.md) on the optimized dictionaries from our model. This can be done by providing the optimized dictionaries from the previous step in the `--optimized-dict-path` flag in their code.

**Comment by samiragarwala** [comment]
The multi-view results for the 3- and 5- view set can be generated by running:
`python ./planeformers/evaluation/eval_multiview.py --multi_view_file <path to multi-view json file> --mp3d_corr_file <path to the mp3d correspondence file> --num_images <3/5> --transformer_ckpt ./models/planeformers_eccv.pt --eval_<corr/camera>`. 

Please note the following:
1) Provide only one of the `--eval_corr` flag to evaluate plane correspondences or the `--eval_camera` flag to evaluate the relative camera pose prediction. Both flags cannot be run together since they operate on GT and predicted boxes respectively.  When running correspondence evaluation, you also need to provide `-dataset_path <path to plane embedding dataset>` so that we can use GT boxes for plane prediction and correspondence evaluation.

2) The test json files that need to be provided to `--multi_view_file` can be found under the multiview_dataset folder in our repository.

3) For simplicity, in our 3- and 5- view sets, we include only those images for which we have GT bounding box information from the 2-view dataset from SparsePlanes to create the final multiview test dataset we report results on in the paper. The `--mp3d_corr_file` flag helps achieve this and I've attached the [3- and 5- view corr files here](https://github.com/samiragarwala/PlaneFormers/files/9847974/mp3d_corr_files.zip) which you can use while running evaluation.

4) Provide 3 or 5 to `--num_images` when running evaluation on the 3- and 5- view set respectively.

5) You will have to update the paths in the files above based on where you save the dataset for the evaluation code to load the images and be able to run. The same is applicable for the two-view evaluation too.

Thank you and please feel free to reach out if you have any other questions!
